### ISSUE TITLE
future tweaks

### ISSUE THREAD

**Issue by anhluong156** [anhluong156/otree#42]
1. quiz question(s) after the practice game / to ensure players know the rules well
2. password at the end of the pre-game survey page, required of players to proceed to start the game (password will be given to them after they have completed the survey on qualtrics)
3. 1p17: change colors for the "you" dots - make them in the same colors as their respective box plots, just in lighter/darker shades
4. 1p12, 1p13: shading for tables
5. 1p16: increase size of dots in the legend
6. 1p15: legend shortening 
7. contri page: add the line "Time Limit: When time runs out, all of your 10 coins will be contributed to the project automatically"

**Comment by anhluong156** [comment]
2 - done

**Comment by anhluong156** [comment]
7 - done

**Comment by anhluong156** [comment]
6 - how come every time i try modifying the legend area "Order of number is.... " and refresh the page, the results page doesn't show anything at all....

**Comment by anhluong156** [comment]
6 - done

**Comment by anhluong156** [comment]
Dude can you take care of number 3 for now. I tried looking at the code of Results.html file and could not find the part where you specify the colors of the dots... 

Also, if you can do the same thing with 1p16 --- because the diamond dots are already in a different shape from the round dots, no need to have them in different colors... just put them in the same colors as the round dots please.

**Comment by elemti** [comment]
will do when im in the mood again

**Comment by anhluong156** [comment]
3 - done
1 & 5 - cancelled
4 - another issue
