### ISSUE TITLE
tweaks for thai2 branch

### ISSUE THREAD

**Issue by anhluong156** [anhluong156/otree#44]
![screen shot 2018-02-08 at 2 08 39 pm](https://user-images.githubusercontent.com/22295306/35993479-7cfdbde6-0cdb-11e8-9595-e575c874d69e.png)

Please **require** a **password** here in order to proceed to the **_next_** page [start the game]. I will give them a password at the end of the survey, so that way I know they complete the whole survey in order to get the password.

**Comment by elemti** [comment]
f4e3751797b0c253e92a919e77f8ee16057258c2

**Comment by anhluong156** [comment]
coolio
