### ISSUE TITLE
asap tasks feb 09

### ISSUE THREAD

**Issue by anhluong156** [anhluong156/otree#45]
![1p14task](https://user-images.githubusercontent.com/22295306/36053759-05090340-0dc1-11e8-9ad3-fc897b3fe7ab.jpg)
![1p15task](https://user-images.githubusercontent.com/22295306/36053762-082b5c30-0dc1-11e8-84cd-542678569d36.jpg)
![1p16task](https://user-images.githubusercontent.com/22295306/36053763-0ad6a64c-0dc1-11e8-89b6-09b72a82e9f7.jpg)

**Comment by anhluong156** [comment]
1p14 - done

**Comment by anhluong156** [comment]
1p14 & 1p15 - done
1p16 - waiting anxiously

**Comment by elemti** [comment]
all done

**Comment by anhluong156** [comment]
ooohhh
