### ISSUE TITLE
asap - bugs in thai2 branch

### ISSUE THREAD

**Issue by anhluong156** [anhluong156/otree#47]
1. overlapping issue in 1p12 | **RESOLVED**
### **2. need horizontal scroll starting from round 3 for 1p16**
(below: screenshot of how they are clumped together like ants making it hard to differentiate ANYTHINGG)
![screen shot 2018-02-14 at 12 18 14 pm](https://user-images.githubusercontent.com/22295306/36218623-099bc148-1183-11e8-877e-f3b9e11b0d42.png)

### **3. need vertical scroll starting from round 3 for 1p17** 
(below: screenshot of how the blox plots are getting increasingly dwarfed as the rounds progress, making it impossible to see anything~~~~)
![screen shot 2018-02-14 at 12 29 03 pm](https://user-images.githubusercontent.com/22295306/36218645-1594a8a2-1183-11e8-9db2-fb7692659546.png)

### **4. cumu. earnings and round-specific earnings are the same in 1p16 - both group & indiv stats**
see screenshot below
![screen shot 2018-02-14 at 12 49 45 pm](https://user-images.githubusercontent.com/22295306/36219660-27cdfbb0-1186-11e8-8800-b56142f0b9da.png)

**Comment by anhluong156** [comment]
overlapping issue in 1p12 resolved
new issues regarding horizontal scroll (1p16) & vertical scroll (1p17)

**Comment by anhluong156** [comment]
new bug regarding cumu earning error in 1p16

**Comment by elemti** [comment]
all resolved
